
# -*- mode: ruby -*-
# vi: set ft=ruby :

VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = "generic/alpine38"
  config.vm.network :private_network, ip: "192.168.58.111"
  config.vm.provider :virtualbox do |vb|
    vb.customize [
      "setextradata", :id,
      "VBoxInternal2/SharedFoldersEnableSymlinksCreate/vagrant-root", "1"
    ]
    vb.customize [
      'modifyvm', :id,
      '--natdnshostresolver1', 'on',
      '--memory', '512',
      '--cpus', '2'
    ]
    config.vm.network :forwarded_port, guest: 3306, host: 3306
    config.vm.network :forwarded_port, guest: 5000, host: 5000
    config.vm.synced_folder "~/PycharmProjects/micro-dvd/", "/opt/micro-dvd"
  end
  config.vm.provision "shell", path: "provision.sh"
end
